version: '3.2'
services:
  redis:
    environment:
      - REDIS_APPENDONLY=yes
    image: 'redis:latest'
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - './redis:/data'

  electroneumd:
    build: electroneumd/.
    image: 'electroneumd:latest'
    restart: always
    ports:
      - "26968:26968"
    volumes:
      - type: volume
        source: wallet
        target: /wallet
        consistant: true
      - type: volume
        source: chain
        target: /root/.electroneum
        consistant: true
    stdin_open: true
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip

  node-cryptonote-pool:
    build: node-cryptonote-pool/.
    image: 'node-cryponight-pool:latest'
    links:
      - redis
      - electroneumd
    ports:
      - "8080:80"
      - "3333:3333"
      - "3008:3008"
      - "3032:3032"
      - "3256:3256"
      - "8336:8336"
    restart: always
    stdin_open: true
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip

volumes:
  wallet:
  chain:
