version: '3'
services:
  redis:
    environment:
      - REDIS_APPENDONLY=yes
    image: 'redis:latest'
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - './redis:/data'
  node-cryptonote-pool:
    build: .
    links:
      - redis
    ports:
      - "8080:80"
      - "3333:3333"
      - "3008:3008"
      - "3032:3032"
      - "3256:3256"
      - "8336:8336"
    restart: always

